name: Build and Release Telegram Bot API for macOS

on:
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sunday at 00:00 UTC
  workflow_dispatch: # Allow manual trigger
  repository_dispatch:
    types: [upstream_update] # Trigger on upstream updates

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [arm64, x86_64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for upstream updates
        id: check
        run: |
          UPSTREAM_COMMIT=$(curl -s https://api.github.com/repos/tdlib/telegram-bot-api/commits/master | jq -r .sha)
          echo "Latest upstream commit: $UPSTREAM_COMMIT"
          LAST_COMMIT=$(cat .last_commit 2>/dev/null || echo "none")
          echo "Last known commit: $LAST_COMMIT"
          if [ "$LAST_COMMIT" != "$UPSTREAM_COMMIT" ]; then
            echo "New upstream commit detected"
            echo "has_new_commit=true" >> $GITHUB_OUTPUT
            echo "commit_sha=$UPSTREAM_COMMIT" >> $GITHUB_OUTPUT
            echo "$UPSTREAM_COMMIT" > .last_commit
          else
            echo "No new upstream commit"
            echo "has_new_commit=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit last commit hash
        if: steps.check.outputs.has_new_commit == 'true'
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .last_commit
          git commit -m "Update last known upstream commit"
          git push

      - name: Install Xcode command-line tools
        if: steps.check.outputs.has_new_commit == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          sudo xcode-select --install || true

      - name: Set up Homebrew
        if: steps.check.outputs.has_new_commit == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/opt/homebrew/bin:/usr/local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        if: steps.check.outputs.has_new_commit == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          brew install gperf cmake openssl@3

      - name: Clone and build telegram-bot-api
        if: steps.check.outputs.has_new_commit == 'true' || github.event_name == 'workflow_dispatch'
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          if [ "$ARCH" = "arm64" ]; then
            OPENSSL_DIR="/opt/homebrew/opt/openssl@3"
            BINARY_NAME="telegram-bot-api-arm64"
          else
            OPENSSL_DIR="/usr/local/opt/openssl@3"
            BINARY_NAME="telegram-bot-api-x86_64"
          fi
          git clone --recursive https://github.com/tdlib/telegram-bot-api.git
          cd telegram-bot-api
          git checkout ${{ steps.check.outputs.commit_sha || 'master' }}
          rm -rf build
          mkdir build
          cd build
          if [ "$ARCH" = "x86_64" ]; then
            arch -x86_64 cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=$OPENSSL_DIR -DCMAKE_INSTALL_PREFIX:PATH=.. ..
            arch -x86_64 cmake --build . --target install
          else
            cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=$OPENSSL_DIR -DCMAKE_INSTALL_PREFIX:PATH=.. ..
            cmake --build . --target install
          fi
          cd ../..
          mv telegram-bot-api/bin/telegram-bot-api telegram-bot-api/bin/$BINARY_NAME
          ls -l telegram-bot-api/bin/$BINARY_NAME
          file telegram-bot-api/bin/$BINARY_NAME

      - name: Upload binary as artifact
        if: steps.check.outputs.has_new_commit == 'true' || github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: telegram-bot-api-${{ matrix.arch }}
          path: telegram-bot-api/bin/telegram-bot-api-${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: steps.check.outputs.has_new_commit == 'true' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare binaries
        run: |
          mkdir -p binaries
          mv artifacts/telegram-bot-api-arm64/telegram-bot-api-arm64 binaries/
          mv artifacts/telegram-bot-api-x86_64/telegram-bot-api-x86_64 binaries/
          ls -l binaries/

      - name: Create or update release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest telegram-bot-api for macOS
          body: |
            telegram-bot-api binaries for macOS (Apple Silicon and Intel).
            Built from commit: ${{ steps.check.outputs.commit_sha || 'master' }}
            - telegram-bot-api-arm64: For Apple Silicon (M1/M2)
            - telegram-bot-api-x86_64: For Intel Macs
          files: |
            binaries/telegram-bot-api-arm64
            binaries/telegram-bot-api-x86_64
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify on success
        if: success()
        run: |
          echo "Successfully built and released telegram-bot-api binaries for macOS"